name: playon
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.5.3+2
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  firebase_core_platform_interface: ^5.0.0
  shared_preferences: ^2.0.15
  permission_handler: ^10.0.0
  json_annotation: ^4.8.1
  get_it: ^7.2.0
  uuid: ^4.2.2
  flutter_local_notifications: ^16.2.0
  pdf: ^3.10.7
  path_provider: ^2.1.1
  syncfusion_flutter_pdfviewer: ^24.1.41

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
